# ------------------------------------------------ #
#              General configuration               #
# ------------------------------------------------ #
# Configure how many times players can interact per second
interact-limit: 1

# Logging - this section defines whether or not to log to the log.txt file
logging:
  enabled: true

# Configure custom protection stones here
protection-stones:
  small-protection:
    meta:
      title: '&3Small Protection'
    block: diamond_block
    radius: 5
    custom-height: -1
    prevent-place: true
    prevent-break: true
    welcome-message: 'Entered %player%s protection'
    leave-message: 'Left %players%s protection'
  medium-protection:
    meta:
      title: '&3Medium Protection'
    block: diamond_block
    radius: 10
    custom-height: -1
    prevent-place: true
    prevent-break: true
    welcome-message: 'Entered %player%s protection'
    leave-message: 'Left %players%s protection'