 name: BiomeProtect
 version: 1.0.1
 description: Allows players to protect regions
 author: firecombat4
 load: POSTWORLD
 main: com.hotmail.steven.biomeprotect.BiomeProtect
 database: false
 
 commands:
   biomeprotect:
     description: Base BiomeProtect command
     aliases: [bp]
     permission: biomecore.gm
     usage: /gm creative|survival|adventure|spectator [player]
 permissions:
   inferno.*:
     description: Gives access to all Inferno commands
     children:
       inferno.flagrate: true
       inferno.burningdeaths: true
       inferno.burningdeaths.others: true
   inferno.flagrate:
     description: Allows you to ignite yourself
     default: true
   inferno.burningdeaths:
     description: Allows you to see how many times you have burned to death
     default: true
   inferno.burningdeaths.others:
     description: Allows you to see how many times others have burned to death
     default: op
     children:
       inferno.burningdeaths: true